Omkar-Sonawane-23/Tourism

src/components/Navbar.jsx
Fixed the Navigation using Link 
Now when we click on places tab in header, it goes to /home
=> Navigation issue

README.md, src/components/Navbar.jsx
I updated the README file with description about how to run the project and how to  contribute in the program.
=> Issue14 update readme

.gitignore, package-lock.json, package.json, src/components/Navbar.jsx
Description
"I've crafted a fully responsive & UI enhanced Navbar, in which i added hamburg icon for navbar on mobile sizes."
This PR fixes  #16 
Issue Title : Improvement of Navbar UI #16
Screenshots :
For Desktop - 
For Tabs - 
For Mobile Phones -
=> Made Responsive Navbar

src/App.jsx, src/pages/NotFound.jsx
1. 404 Not found page added .
2. Routing in App.jsx changed For not found page .
3. CSS in NotFound page added . 
This is under issue No. 79 under GSSOC 24 that is assigned for adding a not found page.
I am attaching a screenshot of that page
=> 404 Not Found Page added  

.gitignore, Data/Detailed.json, README.md, package-lock.json, package.json, src/components/Homeque.jsx, src/components/Navbar.jsx
UI of the Places section updated and made responsive along with the navbar for small screens and broken images resolved.
=> Places_section UI updated and responsive done

src/pages/Explore.jsx, src/pages/Home.jsx, src/pages/Places.js
Added a filter option for the users to select from different options (Historical, Thriller, Calmer) upon selecting a option the selected option will be rendered for the user.
=> Added a filter in the explore section

Data/Detailed.json, src/components/Homeque.jsx
I have updated the card UI and also fixed the image issue
https://github.com/Omkar-Sonawane-23/Tourism/assets/119344874/faff56bd-93bf-4d18-89dc-eadb2e7be636
=> Issue84 updated cards ui & fixing image issue

src/components/Navbar.jsx
successfully added the redirect functionality on navbar logo(Bharat Yatra).
Now users will be redirected to the home page when clicking on the logo enhancing user experience.
https://github.com/Omkar-Sonawane-23/Tourism/assets/119344874/5b772eae-d63f-42b7-976d-747528f8e4e4
=> added-redirect-functionality-on-navbar-logo(Bharat Yatra)

src/App.jsx, src/components/Navbar.jsx, src/pages/ContactUs.jsx, src/pages/Home.jsx
I added contact us page (for resolving any issue of visiters ) and footer section .please @Omkar-Sonawane-23  consider this 
PR and merge this functionality
=> issue #123 :added contact us page and footer

Data/Data.json, src/components/Homeque.jsx
Issue #157 was assigned to me and I have completed the task.
I have added three images which changes after 3 seconds, more images can be added.
I have fixed the conflict which was due to the updated UI.
=> Issue #157  Added Multiple Images which changes in the updated UI

src/components/Homeque.jsx
=> Added a scroll to top button in the /home page.

package-lock.json, package.json, src/pages/Explore.jsx
I had added builded explore with search funtionality by category and states. Also enhanced UI of the page by rebuilding it.
Solved issue #218.
Please give gssoc label and level to issue.
Thank You
=> Builded explore page

src/App.jsx
Fixes Issue : #284
Earlier navbar wasn't visible on every page 
Added Navbar to all the pages
@sameer-soni @Omkar-Sonawane-23 Kindly review this PR
=> Added Navbar to every page

src/pages/Explore.jsx, src/pages/GoToTop.jsx
I've implemented a "go to top" button that, when clicked, smoothly scrolls the user back to the top of the website.
Fixes #271 
Screenshot:
=> [feat]: backtotop button added

src/pages/Home.jsx
Issue : #300 
The header is now responsive for all screen sizes .
https://github.com/Omkar-Sonawane-23/Tourism/assets/118350936/ae55c2d7-6db8-4454-9a00-ce0966024816
=> Header Responsiveness 

src/components/DetailView.jsx, src/components/Details.jsx, src/components/Homeque.jsx, src/pages/Explore.jsx
updating ui for detail page and making it responsive also 
https://github.com/Omkar-Sonawane-23/Tourism/assets/119344874/126c293d-a37d-46d0-8503-c7920238c4e0
=> Updated detail page UI

src/components/Navbar.jsx
Now navbar is responsive and UI is also improved.
In current deployment of website in mobile devices  navbar is not user friendly. and also when we click on elements of navbar it remains in screen which is not good for UI and user experience.
**my issue no is** #215
https://github.com/Omkar-Sonawane-23/Tourism/assets/149225785/27fc64f7-953c-47b0-af94-a4b39f17b244
https://github.com/Omkar-Sonawane-23/Tourism/assets/149225785/b75e8ef7-4503-40a0-b4ad-d5170fa1952c
@sameer-soni  , @Omkar-Sonawane-23  please assign this PR to me and add label in it in small letters also in issue that i have raised. #215
=> Responsive navbar done

src/App.jsx, src/components/Navbar.jsx, src/pages/Home.jsx
issue #320 
This pull request updates the URL address for our "Places" page from "home" to "places". This change is intended to improve the clarity and intuitiveness of our URL structure, making it easier for users to navigate our site.
=> fix: url address for places page "home" to "places"

src/components/Design.jsx, src/components/Faq.css, src/components/Faq.jsx
Bug/ On clicking + symbol in faq section resolved 
#339 
fixes #339 
fixes/on clicking + symbol in faq section resolved #339 
under gssoc'24
on clicking plus symbol in faq section in not working on clicking it works clicking the question resolve
error is resolved 
https://github.com/Omkar-Sonawane-23/Tourism/assets/116994649/0c5b612b-6c41-46d5-bb56-1266175a6457
=> bug resolve

Data/Detailed.json, src/components/Details.jsx
Added FamousFood section also add transitions in it .
Also, its doesn't seem good that it has hover and Travel Tips(just beside famousFood container)  doesn't have so thats why add a hover effect to that too.
attatched video about the changes
https://github.com/Omkar-Sonawane-23/Tourism/assets/96923080/10817f4c-243c-422c-a3e5-6299662eece7
=> #341 Added Famous Food section 

src/components/Design.jsx
I have fixed your FAQ issue. Now anyone can click on the FAQ questions and view the responses. Please see if everything is correct
=> FAQ Issue fixed

src/pages/Login.jsx, src/pages/Register.jsx
1) solved the problem of Input text not visible 
2) Solved the password toggle button not working  in login page
3)Solved self toggle upon writing password issue too
=> #Issue 345 solved
